package dev.jmvg.javajson.exercicio;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

public class ExercicioJson {
    public static void main(String[] args) {

    }
    private static void JSONExampleArray1() {
        //We create a JSONObject from a String containing an array using JSONArray
        //Firstly, we declare an Array in a String

        String arrayStr =
                "["+"true,"+"false,"+ "\"true\","+ "\"false\","+"\"hello\","+"23.45e-4,"+
                        "\"23.45\","+"42,"+"\"43\","+"["+"\"world\""+"],"+
                        "{"+
                        "\"key1\":\"value1\","+
                        "\"key2\":\"value2\","+
                        "\"key3\":\"value3\","+
                        "\"key4\":\"value4\""+
                        "},"+
                        "0,"+"\"-1\""+
                        "]";

        //Then, we initializate the JSONArray thanks to its constructor

        JSONArray array = new JSONArray(arrayStr);
        System.out.println("Values array: "+ array);

        //We convert that array into a JSONObject, but first, we need the labels, so we need another JSONArray with the labels.
        //Here we will use an auxiliary function to get one for the example.

        JSONArray list = listNumberArray(array.size());
        System.out.println("Label Array: "+ list.toString());
        //Now, we construct the JSONObject using both the  value array and the label array.
        JSONObject object = array.toJSONObject(list);
        System.out.println("Final JSONOBject: " + object);
    }

    //This method creates an JSONArray of labels in which those are generated by their positions

    private static JSONArray listNumberArray(int max){
        JSONArray res = new JSONArray();
        for (int i=0; i<max;i++) {
            //The value of the labels must be an String in order to make it work
            res.add(String.valueOf(i));
        }
        return res;
    }

}
